# Generated by Django 3.1.1 on 2020-09-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manager',
        ),
    ]
